### PR TITLE
Generate findOptions only based on primary keys if primary keys exist for the model

### PR DESCRIPTION
**Pull request by kpeng**
The `WHERE` parameters that are generated for the duplicate entries check contain too many columns when primary keys exist. Just searching on the primary key columns should be sufficient in this case.

### CODE REVIEW

**Comment by kpeng** [comment]
@domasx2 Will there be any objection to having this merged? It's a reasonable optimization and should be backwards-compatible with current behavior.

**Comment by domasx2** [comment]
Hi,
thanks for the PR, two questions:

1. Does this make sequelize-fixtures work significantly faster? Have you measured?
2. Why make distinction between explicit primary keys and id field? If auto generated PK is provided, it would also be possible to use that to check for dupes in the same way

**Comment by kpeng** [comment]
Re 1: I haven't gotten the chance to measure yet. For me, the change actually came out of the fact that the WHERE clause generated to check whether the row is already in the table doesn't work for JSON columns, but I imagined users would not be including JSON fields in their primary key constructs anyway.

Re 2: I didn't find anything at the Sequelize level that marked a column as belonging to a primary key if it was auto-generated. Maybe I missed something else, but Sequelize definitely doesn't mark an auto-generated PK ID column with the `primaryKey` attribute.

**Comment by matmar10** [comment]
Is this still needed? JSON columns are supported now yes?

**Comment by kpeng** [comment]
I am going to close this and another one should be opened if it's determined that this is still needed. Thanks for the ping @matmar10.

**Pull request closed without merging**
