### PR TITLE
fix Model check in loader for sequelize v4

### PR DESCRIPTION
**Pull request by usebaz**
Hi,
@domasx2  wath you think about this PR?

This problem slows down the transition to the new version Sequelize.
Thanks!

### CODE REVIEW

**Comment by zazoomauro** [comment]
+1

**Comment by domasx2** [comment]
Hey guys,
Thanks for the PR! I see that some tests are failing though :( I guess this is because new sequelize version is is not backwards-compatible. Would you be willing to investigate and fix the problem?

**Comment by usebaz** [comment]
@domasx2 in test you use sequelize v4?

**Comment by usebaz** [comment]
@domasx2 i set in package.json sequelize `v3` as devDeps, for `v4` need make major changes.
I think it because changes with `BelongsToMany through` logic
http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html

I can make another PR with update major version this package

**Comment by domasx2** [comment]
Thanks! If you could also modify readme to mention that it only works with 3.x.x and not with 4, I will approve it.
An update to make it compat with 4.0.0 is much appreciated also, as currently I don't have much time or motivation to work on this lib

**Comment by usebaz** [comment]
@domasx2 okay, I update readme. 
And when I have free time, fix for v4 and create PR

**Pull request merged**
